
server:
  port: 8081

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:sqlserver://devsvr01;database=SpringBootCamp
    username: sa
    password: admin_T3l!g3nt
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
      dialect: org.hibernate.dialect.SQLServerDialect
    show-sql: true


todo:
  title: Todo App
---

server:
  port: 7000
spring:
  config:
    activate:
      on-profile: dev

dbconfig:
  server: localhostdev
  username: dev
  password: dev

---

server:
  port: 8082
spring:
  config:
    activate:
      on-profile: prod

dbconfig:
  server: localhostprod
  username: prod
  password: prod

