
server:
  port: 8081

spring:
  profiles:
    active: dev

---

server:
  port: 7000
spring:
  config:
    activate:
      on-profile: dev

dbconfig:
  server: localhostdev
  username: dev
  password: dev

---

server:
  port: 8082
spring:
  config:
    activate:
      on-profile: prod

dbconfig:
  server: localhostprod
  username: prod
  password: prod
